/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hack/generate-cluster-scope.go - DO NOT EDIT.

package jobtokenscopes

import (
	"context"
	"strconv"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
	"github.com/pkg/errors"
	gitlab "gitlab.com/gitlab-org/api/client-go/v2"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/crossplane-contrib/provider-gitlab/apis/cluster/projects/v1alpha1"
	"github.com/crossplane-contrib/provider-gitlab/pkg/cluster/clients"
	"github.com/crossplane-contrib/provider-gitlab/pkg/cluster/clients/projects"
	"github.com/crossplane-contrib/provider-gitlab/pkg/common"
)

const (
	errNotJobTokenScopeAllowlistEntry = "managed resource is not a JobTokenScopeAllowlistEntry"
	errIDsNotSet                      = "ProjectID and TargetProjectID must be set"
	errTargetProjectIDNotAnInt        = "TargetProjectID must be an integer"
	errGetAllowlist                   = "cannot get job token inbound allowlist from GitLab"
	errAddToAllowlist                 = "cannot add project to job token inbound allowlist"
	errRemoveFromAllowlist            = "cannot remove project from job token inbound allowlist"

	// allowlistPageSize is the page size used when paging through a project's
	// inbound allowlist.
	allowlistPageSize = 100
)

// SetupJobTokenScopeAllowlistEntry adds a controller that reconciles
// JobTokenScopeAllowlistEntries.
func SetupJobTokenScopeAllowlistEntry(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName("cluster." + v1alpha1.JobTokenScopeAllowlistEntryGroupKind)

	reconcilerOpts := []managed.ReconcilerOption{
		managed.WithExternalConnector(&connector{kube: mgr.GetClient(), newGitlabClientFn: projects.NewJobTokenScopeClient}),
		managed.WithInitializers(),
		managed.WithPollInterval(o.PollInterval),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		reconcilerOpts = append(reconcilerOpts, managed.WithManagementPolicies())
	}

	r := managed.NewReconciler(mgr,
		resource.ManagedKind(v1alpha1.JobTokenScopeAllowlistEntryGroupVersionKind),
		reconcilerOpts...)

	if err := mgr.Add(statemetrics.NewMRStateRecorder(
		mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.JobTokenScopeAllowlistEntryList{}, o.MetricOptions.PollStateMetricInterval)); err != nil {
		return err
	}

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.JobTokenScopeAllowlistEntry{}).
		Complete(r)
}

// SetupJobTokenScopeAllowlistEntryGated adds a controller with CRD gate support.
func SetupJobTokenScopeAllowlistEntryGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := SetupJobTokenScopeAllowlistEntry(mgr, o); err != nil {
			mgr.GetLogger().Error(err, "unable to setup reconciler", "gvk", v1alpha1.JobTokenScopeAllowlistEntryGroupVersionKind.String())
		}
	}, v1alpha1.JobTokenScopeAllowlistEntryGroupVersionKind)
	return nil
}

type connector struct {
	kube              client.Client
	newGitlabClientFn func(cfg common.Config) projects.JobTokenScopeClient
}

func (c *connector) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*v1alpha1.JobTokenScopeAllowlistEntry)
	if !ok {
		return nil, errors.New(errNotJobTokenScopeAllowlistEntry)
	}

	cfg, err := common.GetConfig(ctx, c.kube, cr)
	if err != nil {
		return nil, err
	}

	return &external{client: c.newGitlabClientFn(*cfg)}, nil
}

type external struct {
	client projects.JobTokenScopeClient
}

// Observe pages through the inbound allowlist of ProjectID looking for
// TargetProjectID.
func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.JobTokenScopeAllowlistEntry)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errNotJobTokenScopeAllowlistEntry)
	}

	if cr.Spec.ForProvider.ProjectID == nil || cr.Spec.ForProvider.TargetProjectID == nil {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	targetProjectID, err := strconv.ParseInt(*cr.Spec.ForProvider.TargetProjectID, 10, 64)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errTargetProjectIDNotAnInt)
	}

	found, err := e.entryExists(ctx, *cr.Spec.ForProvider.ProjectID, targetProjectID)
	if err != nil {
		return managed.ExternalObservation{}, err
	}

	if !found {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	cr.Status.AtProvider.ID = *cr.Spec.ForProvider.ProjectID + "-" + *cr.Spec.ForProvider.TargetProjectID
	cr.SetConditions(v2.Available())

	// Every field of an allowlist entry is immutable: an entry either is or is
	// not on the list, so an entry that exists can never be out of date.
	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: true,
	}, nil
}

// entryExists pages through the whole allowlist. Stopping after the first page
// would make an entry on a later page look absent, and the controller would
// keep trying to re-add it.
func (e *external) entryExists(ctx context.Context, projectID string, targetProjectID int64) (bool, error) {
	opt := &gitlab.GetJobTokenInboundAllowListOptions{
		ListOptions: gitlab.ListOptions{
			Page:    1,
			PerPage: allowlistPageSize,
		},
	}

	for {
		allowed, res, err := e.client.GetProjectJobTokenInboundAllowList(projectID, opt, gitlab.WithContext(ctx))
		if err != nil {
			if clients.IsResponseNotFound(res) {
				return false, nil
			}
			return false, errors.Wrap(err, errGetAllowlist)
		}

		for _, p := range allowed {
			if p != nil && p.ID == targetProjectID {
				return true, nil
			}
		}

		if res == nil || res.NextPage == 0 {
			return false, nil
		}
		opt.Page = res.NextPage
	}
}

func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.JobTokenScopeAllowlistEntry)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errNotJobTokenScopeAllowlistEntry)
	}

	if cr.Spec.ForProvider.ProjectID == nil || cr.Spec.ForProvider.TargetProjectID == nil {
		return managed.ExternalCreation{}, errors.New(errIDsNotSet)
	}

	targetProjectID, err := strconv.ParseInt(*cr.Spec.ForProvider.TargetProjectID, 10, 64)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errTargetProjectIDNotAnInt)
	}

	opt := &gitlab.JobTokenInboundAllowOptions{
		TargetProjectID: gitlab.Ptr(targetProjectID),
	}

	_, _, err = e.client.AddProjectToJobScopeAllowList(*cr.Spec.ForProvider.ProjectID, opt, gitlab.WithContext(ctx))
	if err != nil {
		// The entry already being on the list is the state we wanted. A human
		// adding it first should not wedge the controller.
		if projects.IsErrorJobTokenScopeEntryAlreadyExists(err) {
			return managed.ExternalCreation{}, nil
		}
		return managed.ExternalCreation{}, errors.Wrap(err, errAddToAllowlist)
	}

	return managed.ExternalCreation{}, nil
}

// Update is a no-op. An allowlist entry has no mutable field - changing either
// end of it means a different entry - so Observe never reports one as out of
// date and this is never called with anything to do.
func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, nil
}

func (e *external) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.JobTokenScopeAllowlistEntry)
	if !ok {
		return managed.ExternalDelete{}, errors.New(errNotJobTokenScopeAllowlistEntry)
	}

	if cr.Spec.ForProvider.ProjectID == nil || cr.Spec.ForProvider.TargetProjectID == nil {
		return managed.ExternalDelete{}, errors.New(errIDsNotSet)
	}

	targetProjectID, err := strconv.ParseInt(*cr.Spec.ForProvider.TargetProjectID, 10, 64)
	if err != nil {
		return managed.ExternalDelete{}, errors.Wrap(err, errTargetProjectIDNotAnInt)
	}

	res, err := e.client.RemoveProjectFromJobScopeAllowList(*cr.Spec.ForProvider.ProjectID, targetProjectID, gitlab.WithContext(ctx))
	if err != nil {
		// The entry already being gone is the state we wanted.
		if clients.IsResponseNotFound(res) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, errors.Wrap(err, errRemoveFromAllowlist)
	}
	return managed.ExternalDelete{}, nil
}

func (e *external) Disconnect(ctx context.Context) error {
	return nil
}
